name: ors_map_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_google_places_sdk: ^0.4.2+1
  flutter_tts: ^4.2.5
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  assets:
    - assets/car_icon.png
  uses-material-design: true
