name: mapbox_navigation_example
description: "Demonstration of mapbox_navigation Flutter package."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  mapbox_navigation:
    path: ../
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
